### ISSUE TITLE
already available?

### ISSUE THREAD

**Issue by visnup** [ericsoco/baby-name-scraper#2]
I think all of this data is [available as CSVs](https://www.ssa.gov/oact/babynames/limits.html) directly from the Social Security Administration...

**Comment by ericsoco** [comment]
How bout that. Well, it was a good node exercise anyway...

**Comment by visnup** [comment]
I only know because I've been working on https://github.com/visnup/names 😄

**Comment by ericsoco** [comment]
Nice. Do you have it hosted anywhere I can try it out?
